deblur workflow --seqs-fp /workspaces/qiime2_blog/test_data/deblur/data \
                --output-dir /workspaces/qiime2_blog/test_data/deblur \
                --mean-error 0.005 \
                --indel-prob 0.01 \
                --indel-max 3 \
                --trim-length 120 \
                --left-trim-length 0 \
                --min-reads 10 \
                --min-size 2 \
                --jobs-to-start 1 \
                -w --keep-tmp-files